apiVersion: v1
kind: Pod
metadata:
 name: ibankingkubernetessecretspod
 labels:
  applicationName: ibankingkubernetessecretpoc

spec:
 containers:
  - name: ibankingkubernetessecretcontainer1
    image: ramvemula/ibankingkubernetessecrets:1.0
    ports:
     - name: http
       containerPort: 9092
       protocol: TCP
    env:
     - name: db.username
       valueFrom:
        secretKeyRef:
         name: ibankingkubernetessecret  
         key: usernameFromSecret 
     - name: db.password
       valueFrom:
        secretKeyRef: 
         name: ibankingkubernetessecret
         key: passwordFromSecret   
         
        
  