server:
  port: 9092
  
db:
 username: usernameFromSpringBootApplication
 password: passwordFromSpringBootApplication
 
 
management:  endpoints:    web:      exposure:        include: "*"
          endpoint:    health:      probes:        enabled: true