server:
  port: 9094

management:  endpoints:    web:      exposure:        include: "*"
          endpoint:    health:      probes:        enabled: true
spring:   datasource:
    url: jdbc:mysql://localhost:3306/kubernetesdb
    username: root
    password: Secure*123
    driver-class-name: com.mysql.cj.jdbc.Driver  
            
      